import StyleDictionary from 'style-dictionary';

/**
 * Build pipeline:
 *   tokens/tokens.json (W3C DTCG)
 *     └── transformGroup: css (kebab-case, color → hex, dimension → px)
 *           └── format: scss/variables wrapped in :root
 *                 └── src/ds/tokens/_primitives.generated.scss
 */

const HEADER = `// =================================================================
// AUTO-GENERATED by Style Dictionary from tokens/tokens.json
// DO NOT EDIT. Run \`npm run tokens:build\` to regenerate.
// Source: Figma CODE-A-TON Library (synced via Gitfig).
// =================================================================
`;

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    scss: {
      transformGroup: 'css',
      buildPath: 'src/ds/tokens/',
      files: [
        {
          destination: '_primitives.generated.scss',
          format: 'css/variables',
          options: {
            outputReferences: true,
            selector: ':root',
            fileHeader: () => HEADER.split('\n'),
          },
        },
      ],
    },
  },
  log: {
    warnings: 'warn',
    verbosity: 'default',
  },
};
